stages:
  - containerization
  - deploy

variables:
  APPLICATION_NAME: shcp
  DOCKER_IMAGE: ${DOCKER_REGISTRY}/${APPLICATION_NAME}
  CERTIFICATE_DOMAIN: api.shcp.maximemoreillon.com



containerization:
  stage: containerization
  script:
    # If docker registry password provided, attempt login
    - >
      if [ -z ${CONTAINER_REGISTRY_PASSWORD} ];
      then echo "CONTAINER_REGISTRY_PASSWORD not set, skipping login";
      else echo "${CONTAINER_REGISTRY_PASSWORD}" | docker login ${CONTAINER_REGISTRY} --username ${CONTAINER_REGISTRY_USERNAME} --password-stdin;
      fi
    # Copy secrets
    - cp ${SECRETS} ./secrets.js
    # Building and pushing container image
    - docker build -t ${DOCKER_IMAGE} .
    - docker push ${DOCKER_IMAGE}
    - docker image rm ${DOCKER_IMAGE}

deployment:
  stage: deploy
  script:
    - kubectl apply -f deployment.yml
    - kubectl rollout restart deployment/${APPLICATION_NAME}
  environment:
    name: production
